name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x64, arm64, x86]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
        
      - name: Install Dependencies
        run: npm ci

      - name: Bundle with esbuild
        run: |
          mkdir -p dist/build
          npx esbuild server.cjs --bundle --platform=node --target=node18 --outfile=dist/build/server.js

      - name: Package Executable for ${{ matrix.arch }}
        run: |
          pkg ./dist/build/server.js --target node18-${{ matrix.arch }}-linux -o dist/$(node -p "require('./package.json').name + '-v' + require('./package.json').version + '-linux-' + '${{ matrix.arch }}")
      
      - name: Debug show files
        run: ls -la dist
    