name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x64, arm64, x86]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
        
      - name: Install Dependencies
        run: npm ci

      - name: Bundle with esbuild
        run: |
          mkdir -p dist/build
          esbuild server.cjs --bundle --platform=node --target=node18 --outfile=dist/build/server.js

      - name: debug
        run: ls -la dist/build

    