name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x64, arm64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
        
      - name: Install Dependencies
        run: npm ci

      - name: Bundle with esbuild
        run: |
          mkdir -p dist/build
          npx esbuild server.cjs --bundle --platform=node --target=node18 --outfile=dist/build/server.js

      - name: Package Executable for ${{ matrix.arch }}
        run: |
          npx pkg ./dist/build/server.js --target node18-${{ matrix.arch }}-linux -o dist/$(node -p "require('./package.json').name + '-v' + require('./package.json').version + '-linux-' + '${{ matrix.arch }}'")
      
      - name: Upload Artifact for ${{ matrix.arch }}
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.arch }}
          path: dist/*-${{ matrix.arch }}
    
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4

      # Set the version to the tag name (removes the "refs/tags/" prefix)
      - name: Set tag as version
        id: set_version
        run: |
          TAG_NAME=${GITHUB_REF/refs\/tags\//}
          echo "VERSION=$TAG_NAME" >> $GITHUB_ENV
          echo "Tag is $TAG_NAME"

      - name: Check if Release Exists
        id: check_release
        uses: actions/github-script@v7
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            // Remove the refs/tags/ prefix to get the tag name.
            const tag = process.env.GITHUB_REF.replace('refs/tags/', '');
            try {
              await github.rest.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: tag,
              });
              core.info(`Release for tag ${tag} already exists.`);
              core.setOutput('exists', 'true');
            } catch (error) {
              if (error.status === 404) {
                core.info(`No release found for tag ${tag}.`);
                core.setOutput('exists', 'false');
              } else {
                throw error;
              }
            }
          result-encoding: string

      - name: Authenticate GitHub App
        id: auth
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Create GitHub Release
        id: create_release
        if: steps.check_release.outputs.exists == 'false'
        run: |
          echo "Creating release for version ${VERSION}"
          response=$(curl -s -X POST -H "Authorization: Bearer ${{ steps.auth.outputs.token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/releases \
          -d "{
            \"tag_name\": \"${VERSION}\",
            \"name\": \"Release ${VERSION}\",
            \"body\": \"Automated release for version ${VERSION}\",
            \"draft\": false,
            \"prerelease\": false
          }")
          echo "Response: $response"
          echo "UPLOAD_URL=$(echo $response | jq -r .upload_url)" >> $GITHUB_ENV

            # Upload each executable to the release.

  upload_x64:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate GitHub App
        id: auth_x64
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Upload x64 Binary
        run: |
          # Compute the binary filename dynamically.
          binary_file=dist/$(node -p "require('./package.json').name + '-v' + '${{ needs.release.outputs.version }}' + '-linux-x64'")
          echo "Uploading: $binary_file"
          UPLOAD_URL="${{ needs.release.outputs.upload_url }}"
          curl -X POST -H "Authorization: Bearer ${{ steps.auth_x64.outputs.token }}" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @"$binary_file" \
          "$(echo $UPLOAD_URL | sed 's/{?name,label}//')?name=$(basename $binary_file)"

  upload_arm64:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate GitHub App
        id: auth_arm64
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Upload arm64 Binary
        run: |
          # Compute the binary filename dynamically.
          binary_file=dist/$(node -p "require('./package.json').name + '-v' + '${{ needs.release.outputs.version }}' + '-linux-arm64'")
          echo "Uploading: $binary_file"
          UPLOAD_URL="${{ needs.release.outputs.upload_url }}"
          curl -X POST -H "Authorization: Bearer ${{ steps.auth_arm64.outputs.token }}" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @"$binary_file" \
          "$(echo $UPLOAD_URL | sed 's/{?name,label}//')?name=$(basename $binary_file)"
